const kbdkeys = [
  [['key', 'Backquote', '`', '~', 'ё', 'Ё'], ['key', 'Digit1', '1', '!', '1', '!'], ['key', 'Digit2', '2', '@', '2', '@'], ['key', 'Digit3', '3', '#', '3', '#'], ['key', 'Digit4', '4', '$', '4', '$'], ['key', 'Digit5', '5', '%', '5', '%'], ['key', 'Digit6', '6', '^', '6', '^'], ['key', 'Digit7', '7', '&', '7', '&'], ['key', 'Digit8', '8', '*', '8', '*'], ['key', 'Digit9', '9', '(', '9', '('], ['key', 'Digit0', '0', ')', '0', ')'], ['key', 'Minus', '-', '_', '-', '_'], ['key', 'Equal', '=', '+', '=', '+'], ['key backspace', 'Backspace', 'Backspace', 'Backspace', 'Backspace', 'Backspace']],
  [['key tab', 'Tab', 'Tab', 'Tab', 'Tab', 'Tab'], ['key', 'KeyQ', 'q', 'Q', 'й', 'Й'], ['key', 'KeyW', 'w', 'W', 'ц', 'Ц'], ['key', 'KeyE', 'e', 'E', 'у', 'У'], ['key', 'KeyR', 'r', 'R', 'к', 'К'], ['key', 'KeyT', 't', 'T', 'е', 'Е'], ['key', 'KeyY', 'y', 'Y', 'н', 'Н'], ['key', 'KeyU', 'u', 'U', 'г', 'Г'], ['key', 'KeyI', 'i', 'I', 'ш', 'Ш'], ['key', 'KeyO', 'o', 'O', 'щ', 'Щ'], ['key', 'KeyP', 'p', 'P', 'з', 'З'], ['key bracket-left', 'BracketLeft', '[', '{', 'х', 'Х'], ['key bracket-right', 'BracketRight', ']', '}', 'ъ', 'Ъ'], ['key backslash', 'Backslash', '\\', '|', '\\', '/'], ['key delete', 'Delete', 'DEL', 'DEL', 'DEL', 'DEL']],
  [['key capslock', 'CapsLock', 'Caps Lock', 'Caps Lock', 'Caps Lock', 'Caps Lock'], ['key', 'KeyA', 'a', 'A', 'ф', 'Ф'], ['key', 'KeyS', 's', 'S', 'ы', 'Ы'], ['key', 'KeyD', 'd', 'D', 'в', 'В'], ['key', 'KeyF', 'f', 'F', 'а', 'А'], ['key', 'KeyG', 'g', 'G', 'п', 'П'], ['key', 'KeyH', 'h', 'H', 'р', 'Р'], ['key', 'KeyJ', 'j', 'J', 'о', 'О'], ['key', 'KeyK', 'k', 'K', 'л', 'Л'], ['key', 'KeyL', 'l', 'L', 'д', 'Д'], ['key', 'Semicolon', ';', ':', 'ж', 'Ж'], ['key', 'Quote', '\'', '"', 'э', 'Э'], ['key enter', 'Enter', 'Enter', 'Enter', 'Enter', 'Enter']],
  [['key shift-left', 'ShiftLeft', 'Shift', 'Shift', 'Shift', 'Shift'], ['key', 'KeyZ', 'z', 'Z', 'я', 'Я'], ['key', 'KeyX', 'x', 'X', 'ч', 'Ч'], ['key', 'KeyC', 'c', 'C', 'с', 'С'], ['key', 'KeyV', 'v', 'V', 'м', 'М'], ['key', 'KeyB', 'b', 'B', 'и', 'И'], ['key', 'KeyN', 'n', 'N', 'т', 'Т'], ['key', 'KeyM', 'm', 'M', 'ь', 'Ь'], ['key', 'Comma', ',', '<', 'б', 'Б'], ['key', 'Period', '.', '>', 'ю', 'Ю'], ['key slash', 'Slash', '/', '?', '.', ','], ['key arrow-up', 'ArrowUp', '↑', '↑', '↑', '↑'], ['key shift-right', 'ShiftRight', 'Shift', 'Shift', 'Shift', 'Shift']],
  [['key ctrl-left', 'ControlLeft', 'Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'], ['key win', 'MetaLeft', 'Win', 'Win', 'Win', 'Win'], ['key alt-left', 'AltLeft', 'Alt', 'Alt', 'Alt', 'Alt'], ['key space', 'Space', ' ', ' ', ' ', ' '], ['key alt-right', 'AltRight', 'Alt', 'Alt', 'Alt', 'Alt'], ['key ctrl-right', 'ControlRight', 'Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'], ['key left', 'ArrowLeft', '←', '←', '←', '←'], ['key down', 'ArrowDown', '↓', '↓', '↓', '↓'], ['key right', 'ArrowRight', '→', '→', '→', '→']],
];

export default kbdkeys;
